import { useState } from 'react';
import Link from 'next/link';
import { 
  HiQuestionMarkCircle, HiChevronDown, HiChevronUp, HiHome,
  HiLightningBolt, HiDatabase, HiUserGroup, HiClipboardCheck,
  HiMail, HiCog, HiSupport
} from 'react-icons/hi';

const faqCategories = [
  {
    id: 'getting-started',
    title: 'Getting Started',
    icon: HiLightningBolt,
    color: '#f59e0b',
    questions: [
      {
        q: 'What is Strikezone?',
        a: 'Strikezone is a Business Development as a Service (BDaaS) platform that helps you identify your most valuable customers (Top 20%), understand their common traits (ICP), find similar companies to target (Lookalikes), and generate personalized outreach messages using AI.'
      },
      {
        q: 'How do I get started?',
        a: 'Start by uploading your ERP data (Customers.csv, Orders.csv, OrderLines.csv, Products.csv) on the CEO Dashboard. The system will automatically analyze your data, calculate Top 20% customers by gross margin, and generate your Ideal Customer Profile (ICP).'
      },
      {
        q: 'What data formats are supported?',
        a: 'Currently, we support CSV files exported from any ERP system. The required files are: Customers.csv (customer information), Orders.csv (order headers), OrderLines.csv (order line items), and Products.csv (product catalog). Each file should have headers in the first row.'
      },
      {
        q: 'How long does the initial analysis take?',
        a: 'The initial data upload and analysis typically takes 1-5 minutes depending on the size of your data. Top 20% calculation and ICP generation are nearly instant once the data is loaded.'
      },
    ]
  },
  {
    id: 'data-upload',
    title: 'Data & Upload',
    icon: HiDatabase,
    color: '#2563eb',
    questions: [
      {
        q: 'What fields are required in each CSV file?',
        a: `**Customers.csv**: customer_id (required), customer_name, industry, naics, city, state, country, employee_count, annual_revenue\n\n**Orders.csv**: order_id (required), order_date, customer_id, order_revenue, order_cogs, gross_margin\n\n**OrderLines.csv**: order_line_id (required), order_id, customer_id, order_date, product_id, product_category, quantity, line_revenue, line_cogs\n\n**Products.csv**: product_id (required), product_name, product_category`
      },
      {
        q: 'Can I upload data from multiple ERP systems?',
        a: 'Yes! Strikezone is ERP-agnostic. You can export data from SAP, Oracle, NetSuite, QuickBooks, or any other system. Just ensure your CSV files follow the required column structure.'
      },
      {
        q: 'Is my data secure?',
        a: 'Yes. Your data is stored in a secure PostgreSQL database and is never shared with third parties. All API connections use HTTPS encryption. For enterprise deployments, we support on-premise installation.'
      },
      {
        q: 'How do I update my data?',
        a: 'Simply upload new CSV files with the same structure. The system uses upsert logic - existing records are updated and new records are inserted. You can also recalculate metrics after uploading new data.'
      },
    ]
  },
  {
    id: 'top20-icp',
    title: 'Top 20% & ICP',
    icon: HiUserGroup,
    color: '#10b981',
    questions: [
      {
        q: 'What is the "Top 20%" analysis?',
        a: 'The Top 20% analysis identifies your most valuable customers based on gross margin contribution. These customers typically represent the majority of your profit (often 70-80% or more). Understanding these customers helps you find more like them.'
      },
      {
        q: 'How is the Ideal Customer Profile (ICP) generated?',
        a: 'The ICP is generated by analyzing common traits across your Top 20% customers. We calculate "lift" scores that show how much more likely a trait appears in your best customers vs. others. Traits with high lift scores define your ICP.'
      },
      {
        q: 'What traits are analyzed?',
        a: 'We analyze: Industry, Geographic location (State/Region), NAICS codes, Employee count ranges, Annual revenue ranges, Product categories purchased, Order frequency, and Average order value. Custom traits can be added based on your data.'
      },
      {
        q: 'Can I adjust the Top 20% threshold?',
        a: 'The default is 20% (the Pareto principle), but you can recalculate using different percentiles (e.g., Top 10%, Top 30%) by modifying the calculation parameters in the backend configuration.'
      },
    ]
  },
  {
    id: 'targeting',
    title: 'Target & Approval',
    icon: HiClipboardCheck,
    color: '#f59e0b',
    questions: [
      {
        q: 'How are lookalike targets generated?',
        a: 'Lookalike targets are companies that match your ICP traits. We can generate them from multiple sources: Apollo.io (firmographic search), ZoomInfo (AI-powered similarity), 6sense (intent + predictive), Power BI exports, or Win-back campaigns from inactive customers.'
      },
      {
        q: 'What is the Approval Portal?',
        a: 'The Approval Portal is where you review AI-suggested target companies before they enter your outreach pipeline. You can approve, reject, or skip targets, edit tier rankings, and add notes. This ensures human oversight of all targeting decisions.'
      },
      {
        q: 'What do the Tier rankings mean?',
        a: '**Tier A**: Highest priority - strong ICP match, high opportunity score. Target immediately.\n**Tier B**: Good fit - moderate ICP match. Worth pursuing after Tier A.\n**Tier C**: Lower priority - partial ICP match. Consider for later outreach.'
      },
      {
        q: 'What is a "Win-back" target?',
        a: 'Win-back targets are existing customers who have become inactive (no orders in X days) but were historically high-margin. They\'re often easier to convert than new prospects since they already know your company.'
      },
    ]
  },
  {
    id: 'messaging',
    title: 'AI Messaging',
    icon: HiMail,
    color: '#8b5cf6',
    questions: [
      {
        q: 'How does AI message generation work?',
        a: 'We use OpenAI\'s GPT models to generate personalized outreach messages. The AI considers the contact\'s name, title, company, industry, and your product/service to create relevant, engaging messages. You can also provide custom instructions.'
      },
      {
        q: 'What types of messages can be generated?',
        a: 'We support three message types:\n- **Email**: Full email with subject line and body\n- **LinkedIn**: Connection request or InMail message\n- **Call Script**: Talking points for cold calls'
      },
      {
        q: 'Do I need to review messages before sending?',
        a: 'Yes! All AI-generated messages go through the Approval Portal. You can approve them as-is, edit them, or reject them. This ensures every outreach message meets your quality standards.'
      },
      {
        q: 'Can I use my own templates?',
        a: 'Yes. You can create message templates in the system that the AI will use as a starting point. Templates can include variables like {{first_name}}, {{company}}, etc. that get replaced with real data.'
      },
    ]
  },
  {
    id: 'technical',
    title: 'Technical & Setup',
    icon: HiCog,
    color: '#6b7280',
    questions: [
      {
        q: 'What are the system requirements?',
        a: 'The platform requires: Node.js 18+, PostgreSQL 14+, and a modern web browser. For AI features, you\'ll need an OpenAI API key. For lookalike generation, you\'ll need API keys from Apollo, ZoomInfo, or 6sense.'
      },
      {
        q: 'How do I set up API keys?',
        a: 'Add your API keys to the backend/.env file:\n- OPENAI_API_KEY (for AI messaging)\n- APOLLO_API_KEY (for Apollo lookaliikes)\n- ZOOMINFO_API_KEY (for ZoomInfo)\n- SIXSENSE_API_KEY (for 6sense)'
      },
      {
        q: 'Can I self-host Strikezone?',
        a: 'Yes! Strikezone can be deployed on-premise or in your own cloud environment. The entire stack (frontend, backend, database) can run on a single server or be distributed across multiple instances for scale.'
      },
      {
        q: 'How do I reset my database?',
        a: 'Run the database initialization script: `node backend/src/scripts/initDb.js`. This will drop and recreate all tables. WARNING: This deletes all existing data.'
      },
    ]
  },
  {
    id: 'troubleshooting',
    title: 'Troubleshooting',
    icon: HiSupport,
    color: '#ef4444',
    questions: [
      {
        q: 'Upload failed with "Failed to connect to server"',
        a: 'Make sure the backend server is running (npm run dev in the backend folder). Check that NEXT_PUBLIC_API_URL in your frontend .env points to the correct backend URL (default: http://localhost:5000).'
      },
      {
        q: 'Top 20% calculation shows 0 customers',
        a: 'Ensure you\'ve uploaded both Customers.csv and Orders.csv files. The calculation requires order data to compute gross margins. Also verify that order_revenue and order_cogs fields have numeric values.'
      },
      {
        q: 'Lookalike generation returns empty results',
        a: 'Check that your API key is correctly set in backend/.env. For Apollo, ensure your search query matches companies in their database. You may need to broaden your search criteria.'
      },
      {
        q: 'AI messages are not being generated',
        a: 'Verify your OPENAI_API_KEY is valid and has available credits. Check the browser console and backend logs for specific error messages. The OpenAI API occasionally has rate limits.'
      },
    ]
  },
];

function FAQItem({ question, answer, isOpen, onToggle }) {
  return (
    <div style={{
      border: '1px solid #e5e7eb',
      borderRadius: '8px',
      marginBottom: '10px',
      overflow: 'hidden',
    }}>
      <button
        onClick={onToggle}
        style={{
          width: '100%',
          padding: '15px 20px',
          display: 'flex',
          justifyContent: 'space-between',
          alignItems: 'center',
          background: isOpen ? '#f9fafb' : 'white',
          border: 'none',
          cursor: 'pointer',
          textAlign: 'left',
        }}
      >
        <span style={{ fontWeight: '600', fontSize: '15px', color: '#1f2937' }}>{question}</span>
        {isOpen ? <HiChevronUp size={20} color="#6b7280" /> : <HiChevronDown size={20} color="#6b7280" />}
      </button>
      {isOpen && (
        <div style={{
          padding: '15px 20px',
          borderTop: '1px solid #e5e7eb',
          background: '#fafafa',
          fontSize: '14px',
          lineHeight: '1.7',
          color: '#4b5563',
          whiteSpace: 'pre-wrap',
        }}>
          {answer}
        </div>
      )}
    </div>
  );
}

export default function FAQPage() {
  const [openItems, setOpenItems] = useState({});
  const [searchQuery, setSearchQuery] = useState('');

  const toggleItem = (categoryId, index) => {
    const key = `${categoryId}-${index}`;
    setOpenItems(prev => ({ ...prev, [key]: !prev[key] }));
  };

  const filteredCategories = searchQuery.trim()
    ? faqCategories.map(cat => ({
        ...cat,
        questions: cat.questions.filter(
          q => q.q.toLowerCase().includes(searchQuery.toLowerCase()) ||
               q.a.toLowerCase().includes(searchQuery.toLowerCase())
        )
      })).filter(cat => cat.questions.length > 0)
    : faqCategories;

  return (
    <div style={{ padding: '30px', fontFamily: 'system-ui, sans-serif', maxWidth: '900px', margin: '0 auto', background: '#f9fafb', minHeight: '100vh' }}>
      {/* Header */}
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '30px' }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: '12px' }}>
          <HiQuestionMarkCircle size={36} color="#2563eb" />
          <div>
            <h1 style={{ margin: 0, fontSize: '28px' }}>Frequently Asked Questions</h1>
            <p style={{ margin: '5px 0 0', color: '#6b7280' }}>Find answers to common questions about Strikezone</p>
          </div>
        </div>
        <Link href="/">
          <button style={{
            padding: '10px 16px',
            background: '#f3f4f6',
            color: '#374151',
            border: '1px solid #d1d5db',
            borderRadius: '8px',
            cursor: 'pointer',
            display: 'flex',
            alignItems: 'center',
            gap: '6px',
            fontWeight: '500',
          }}>
            <HiHome size={18} /> Home
          </button>
        </Link>
      </div>

      {/* Search */}
      <div style={{ marginBottom: '30px' }}>
        <input
          type="text"
          placeholder="Search FAQs..."
          value={searchQuery}
          onChange={(e) => setSearchQuery(e.target.value)}
          style={{
            width: '100%',
            padding: '14px 18px',
            fontSize: '16px',
            border: '1px solid #d1d5db',
            borderRadius: '10px',
            outline: 'none',
          }}
        />
      </div>

      {/* Quick Links */}
      <div style={{
        display: 'flex',
        gap: '10px',
        flexWrap: 'wrap',
        marginBottom: '30px',
      }}>
        {faqCategories.map(cat => {
          const Icon = cat.icon;
          return (
            <a
              key={cat.id}
              href={`#${cat.id}`}
              style={{
                display: 'flex',
                alignItems: 'center',
                gap: '6px',
                padding: '8px 14px',
                background: 'white',
                border: '1px solid #e5e7eb',
                borderRadius: '20px',
                textDecoration: 'none',
                color: '#374151',
                fontSize: '13px',
                fontWeight: '500',
              }}
            >
              <Icon size={16} color={cat.color} />
              {cat.title}
            </a>
          );
        })}
      </div>

      {/* FAQ Categories */}
      {filteredCategories.map(category => {
        const Icon = category.icon;
        return (
          <div key={category.id} id={category.id} style={{ marginBottom: '35px' }}>
            <div style={{
              display: 'flex',
              alignItems: 'center',
              gap: '10px',
              marginBottom: '15px',
            }}>
              <div style={{
                background: `${category.color}15`,
                padding: '10px',
                borderRadius: '10px',
              }}>
                <Icon size={24} color={category.color} />
              </div>
              <h2 style={{ margin: 0, fontSize: '20px', color: '#1f2937' }}>{category.title}</h2>
            </div>

            <div style={{ background: 'white', borderRadius: '12px', padding: '15px', boxShadow: '0 2px 8px rgba(0,0,0,0.05)' }}>
              {category.questions.map((item, idx) => (
                <FAQItem
                  key={idx}
                  question={item.q}
                  answer={item.a}
                  isOpen={openItems[`${category.id}-${idx}`]}
                  onToggle={() => toggleItem(category.id, idx)}
                />
              ))}
            </div>
          </div>
        );
      })}

      {filteredCategories.length === 0 && (
        <div style={{ textAlign: 'center', padding: '40px', color: '#6b7280' }}>
          No FAQs match your search. Try different keywords.
        </div>
      )}

      {/* Still Need Help */}
      <div style={{
        background: 'linear-gradient(135deg, #2563eb 0%, #7c3aed 100%)',
        borderRadius: '12px',
        padding: '30px',
        textAlign: 'center',
        color: 'white',
        marginTop: '40px',
      }}>
        <h3 style={{ margin: '0 0 10px' }}>Still have questions?</h3>
        <p style={{ margin: '0 0 20px', opacity: 0.9 }}>
          Check out our detailed Platform Guide or contact support.
        </p>
        <div style={{ display: 'flex', gap: '15px', justifyContent: 'center' }}>
          <Link href="/guide">
            <button style={{
              background: 'white',
              color: '#2563eb',
              padding: '12px 24px',
              borderRadius: '8px',
              border: 'none',
              cursor: 'pointer',
              fontWeight: '600',
            }}>
              View Platform Guide
            </button>
          </Link>
        </div>
      </div>

      <div style={{ marginTop: '30px', textAlign: 'center', color: '#9ca3af', fontSize: '12px' }}>
        Strikezone Platform • BDaaS Solution
      </div>
    </div>
  );
}
