import Link from 'next/link';
import { 
  HiHome, HiChartBar, HiUserGroup, HiClipboardCheck, HiMail, 
  HiLightningBolt, HiArrowRight, HiCheckCircle, HiDatabase,
  HiSparkles, HiDocumentReport
} from 'react-icons/hi';

const pages = [
  {
    name: 'CEO Dashboard',
    path: '/ceo-dashboard',
    icon: HiChartBar,
    color: '#2563eb',
    phase: 'Phase 1',
    required: true,
    description: 'Executive overview of your Top 20% customer analysis and business metrics.',
    features: [
      'Upload ERP data (Customers, Orders, Products, OrderLines)',
      'View Top 20% customers by gross margin contribution',
      'See revenue distribution and customer concentration',
      'Identify your most valuable customer segments',
      'Track key performance indicators (KPIs)',
    ],
    workflow: 'Start here! Upload your data files to begin the analysis process.',
  },
  {
    name: 'ICP Dashboard',
    path: '/icp-dashboard',
    icon: HiUserGroup,
    color: '#10b981',
    phase: 'Phase 2',
    required: true,
    description: 'Ideal Customer Profile analysis derived from your Top 20% customers.',
    features: [
      'View common traits across top customers (industry, location, size)',
      'See revenue and employee distribution patterns',
      'Identify geographic concentrations',
      'Understand what makes your best customers similar',
      'Export ICP traits for targeting',
    ],
    workflow: 'After uploading data, analyze the traits that your best customers share.',
  },
  {
    name: 'Approval Portal',
    path: '/approval-portal',
    icon: HiClipboardCheck,
    color: '#f59e0b',
    phase: 'Phase 3',
    required: true,
    description: 'Review and approve lookalike target companies generated by the system.',
    features: [
      'Review AI-suggested lookalike companies',
      'See similarity scores and tier rankings',
      'Approve, reject, or skip target companies',
      'Filter by status (pending, approved, rejected)',
      'Bulk approve or reject targets',
      'Export approved targets for outreach',
    ],
    workflow: 'After ICP analysis, review and approve target companies that match your profile.',
  },
  {
    name: 'Messaging Portal',
    path: '/messaging-portal',
    icon: HiMail,
    color: '#8b5cf6',
    phase: 'Phase 4B',
    required: true,
    description: 'Generate and approve AI-powered personalized outreach messages.',
    features: [
      'Generate personalized emails using ChatGPT',
      'Create LinkedIn connection messages',
      'Generate cold call scripts',
      'Review and edit AI-generated content',
      'Approve, reject, or modify messages',
      'Export approved messages for campaigns',
    ],
    workflow: 'After enriching contacts, generate and approve personalized messages.',
  },
];

const workflowSteps = [
  { step: 1, title: 'Upload Data', desc: 'Upload your ERP exports (Customers, Orders, Products, OrderLines)', page: '/ceo-dashboard' },
  { step: 2, title: 'Analyze Top 20%', desc: 'System calculates top customers by gross margin', page: '/ceo-dashboard' },
  { step: 3, title: 'Generate ICP', desc: 'Identify traits shared by your best customers', page: '/icp-dashboard' },
  { step: 4, title: 'Find Lookalikes', desc: 'Search for companies matching your ICP', page: '/approval-portal' },
  { step: 5, title: 'Approve Targets', desc: 'Review and approve target companies', page: '/approval-portal' },
  { step: 6, title: 'Enrich Contacts', desc: 'Find decision-makers at approved companies', page: '/messaging-portal' },
  { step: 7, title: 'Generate Messages', desc: 'Create AI-powered personalized outreach', page: '/messaging-portal' },
  { step: 8, title: 'Review & Send', desc: 'Approve messages and export for campaigns', page: '/messaging-portal' },
];

export default function GuidePage() {
  return (
    <div style={{ padding: '30px', fontFamily: 'system-ui, sans-serif', maxWidth: '1200px', margin: '0 auto', background: '#f9fafb', minHeight: '100vh' }}>
      {/* Header */}
      <div style={{ textAlign: 'center', marginBottom: '40px' }}>
        <h1 style={{ fontSize: '32px', marginBottom: '10px', display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '12px' }}>
          <HiLightningBolt size={36} color="#f59e0b" />
          Strikezone Platform Guide
        </h1>
        <p style={{ color: '#6b7280', fontSize: '18px', maxWidth: '700px', margin: '0 auto' }}>
          Transform your ERP data into targeted sales outreach. 
          Follow the workflow below to identify your ideal customers and generate personalized messages.
        </p>
      </div>

      {/* Workflow Steps */}
      <div style={{ background: 'white', borderRadius: '12px', padding: '25px', boxShadow: '0 2px 8px rgba(0,0,0,0.08)', marginBottom: '40px' }}>
        <h2 style={{ fontSize: '20px', marginBottom: '20px', display: 'flex', alignItems: 'center', gap: '8px' }}>
          <HiArrowRight size={24} color="#2563eb" /> End-to-End Workflow
        </h2>
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: '15px' }}>
          {workflowSteps.map((step, idx) => (
            <Link key={step.step} href={step.page} style={{ textDecoration: 'none' }}>
              <div style={{
                background: '#f8fafc',
                borderRadius: '8px',
                padding: '15px',
                border: '1px solid #e2e8f0',
                cursor: 'pointer',
                transition: 'all 0.2s',
              }}>
                <div style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '8px' }}>
                  <span style={{
                    background: '#2563eb',
                    color: 'white',
                    width: '24px',
                    height: '24px',
                    borderRadius: '50%',
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'center',
                    fontSize: '12px',
                    fontWeight: 'bold',
                  }}>
                    {step.step}
                  </span>
                  <span style={{ fontWeight: '600', fontSize: '14px', color: '#1f2937' }}>{step.title}</span>
                </div>
                <p style={{ fontSize: '12px', color: '#6b7280', margin: 0 }}>{step.desc}</p>
              </div>
            </Link>
          ))}
        </div>
      </div>

      {/* Page Cards */}
      <h2 style={{ fontSize: '24px', marginBottom: '20px' }}>Platform Pages</h2>
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(2, 1fr)', gap: '20px' }}>
        {pages.map((page) => {
          const Icon = page.icon;
          return (
            <div key={page.path} style={{
              background: 'white',
              borderRadius: '12px',
              padding: '25px',
              boxShadow: '0 2px 8px rgba(0,0,0,0.08)',
              borderTop: `4px solid ${page.color}`,
            }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: '12px', marginBottom: '15px' }}>
                <div style={{
                  background: `${page.color}15`,
                  padding: '12px',
                  borderRadius: '10px',
                }}>
                  <Icon size={28} color={page.color} />
                </div>
                <div>
                  <h3 style={{ margin: 0, fontSize: '20px' }}>{page.name}</h3>
                  <span style={{
                    background: page.color,
                    color: 'white',
                    padding: '2px 8px',
                    borderRadius: '10px',
                    fontSize: '11px',
                    fontWeight: '600',
                  }}>
                    {page.phase}
                  </span>
                </div>
              </div>

              <p style={{ color: '#4b5563', marginBottom: '15px', lineHeight: '1.5' }}>
                {page.description}
              </p>

              <div style={{ background: '#f0fdf4', padding: '12px', borderRadius: '8px', marginBottom: '15px' }}>
                <strong style={{ color: '#166534', fontSize: '13px' }}>Workflow Tip:</strong>
                <p style={{ margin: '5px 0 0', fontSize: '13px', color: '#15803d' }}>{page.workflow}</p>
              </div>

              <h4 style={{ fontSize: '14px', marginBottom: '10px', color: '#374151' }}>What you can do:</h4>
              <ul style={{ margin: 0, paddingLeft: '20px' }}>
                {page.features.map((feature, idx) => (
                  <li key={idx} style={{ fontSize: '13px', color: '#6b7280', marginBottom: '5px', display: 'flex', alignItems: 'flex-start', gap: '6px' }}>
                    <HiCheckCircle size={14} color="#10b981" style={{ marginTop: '3px', flexShrink: 0 }} />
                    <span>{feature}</span>
                  </li>
                ))}
              </ul>

              <Link href={page.path}>
                <button style={{
                  marginTop: '20px',
                  background: page.color,
                  color: 'white',
                  padding: '10px 20px',
                  borderRadius: '8px',
                  border: 'none',
                  cursor: 'pointer',
                  fontWeight: '500',
                  display: 'flex',
                  alignItems: 'center',
                  gap: '8px',
                  width: '100%',
                  justifyContent: 'center',
                }}>
                  Open {page.name} <HiArrowRight size={16} />
                </button>
              </Link>
            </div>
          );
        })}
      </div>

      {/* Quick Start */}
      <div style={{ marginTop: '40px', background: 'linear-gradient(135deg, #2563eb 0%, #7c3aed 100%)', borderRadius: '12px', padding: '30px', color: 'white', textAlign: 'center' }}>
        <h2 style={{ marginBottom: '15px' }}>Ready to Get Started?</h2>
        <p style={{ opacity: 0.9, marginBottom: '20px', maxWidth: '600px', margin: '0 auto 20px' }}>
          Begin by uploading your ERP data to the CEO Dashboard. The platform will guide you through each step of the process.
        </p>
        <Link href="/ceo-dashboard">
          <button style={{
            background: 'white',
            color: '#2563eb',
            padding: '12px 30px',
            borderRadius: '8px',
            border: 'none',
            cursor: 'pointer',
            fontWeight: '600',
            fontSize: '16px',
            display: 'inline-flex',
            alignItems: 'center',
            gap: '8px',
          }}>
            <HiDatabase size={20} /> Start with CEO Dashboard
          </button>
        </Link>
      </div>

      <div style={{ marginTop: '30px', textAlign: 'center', color: '#9ca3af', fontSize: '12px' }}>
        Strikezone Platform • BDaaS Solution
      </div>
    </div>
  );
}
